document_dir: onc_documents

llm:
  provider: groq  # groq or ollama only (OpenAI removed)
  groq:
    model: llama3-70b-8192
    temperature: 0.1
    api_key_env: GROQ_API_KEY
  ollama:
    model: llama3.1
    temperature: 0.1
  # OpenAI configuration removed - using Groq/Ollama only

embeddings:
  provider: mistral
  model: mistral-embed

processing:
  chunk_size: 500
  chunk_overlap: 50
  batch_size: 20

retrieval:
  k: 8
  similarity_threshold: 0.75

vector_store:
  provider: chroma  # chroma or sklearn
  persist_directory: onc_vectorstore
  force_rebuild: false
  collection_name: onc_documents

query_routing:
  use_llm_routing: true  # Enable LLM-based query routing
  vector_threshold: 0.1
  database_threshold: 0.05
  hybrid_threshold: 0.15

conversation:
  max_history_length: 10  # Maximum conversation exchanges to remember
  context_window_minutes: 30  # Minutes after which context becomes less relevant

ocean_responses:
  enhanced_formatting: false  # Enable natural language responses for ocean data (temporarily disabled for debugging)
  include_educational_context: true  # Add educational explanations
  show_technical_summary: true  # Include technical details at the end

onc_specific:
  cambridge_bay_focus: true
  instrument_priority:
    - CTD
    - hydrophone
    - ADCP
    - camera
    - seismometer
  data_types:
    - temperature
    - salinity
    - pressure
    - acoustic
    - ice_conditions
  observatories:
    - Cambridge Bay
    - Folger Passage
    - Strait of Georgia
    - Barkley Canyon